name: Build and Publish the Images

# Controls when the workflow will run
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      ignore_file_changes:
        description: Rebuild the images regardless of whether the dependent files have changed
        type: boolean
        default: false
      ignore_cache:
        description: Do not used cached images when building
        type: boolean
        default: false
      coursekata_ref:
        description: The commit ref to use for UCLATALL/coursekata-r
        type: string
        default: 0.3.3

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Actions repo: 
      - uses: actions/checkout@v2

      # Actions repo: https://github.com/dorny/paths-filter
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            base:
              - 'r-notebook.Dockerfile'
              - 'scripts/**'
            deepnote:
              - 'deepnote.Dockerfile'
              - 'r-notebook.Dockerfile'
              - 'scripts/**'

      # Actions repo: https://github.com/elgohr/Publish-Docker-Github-Action
      - name: Base image
        if: steps.changes.outputs.base == 'true' || github.event.inputs.ignore_file_changes
        uses: elgohr/Publish-Docker-Github-Action@3.04
        env:
          COURSEKATA_REF: ${{ github.event.inputs.coursekata_ref }}
        with:
          name: uclatall/r-notebook
          dockerfile: r-notebook.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          snapshot: true
          default_branch: main
          cache: ${{ !github.event.inputs.ignore_cache }}
          buildargs: COURSEKATA_REF

      - name: Deepnote name
        if: steps.changes.outputs.deepnote == 'true' || github.event.inputs.ignore_file_changes
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: uclatall/deepnote
          dockerfile: deepnote.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          snapshot: true
          default_branch: main
          cache: ${{ !github.event.inputs.ignore_cache }}
