name: Rebuild an image

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      image:
        description: |
          The name of the image to rebuild
        type: choice
        options:
          - base
          - deepnote
          - binder
        required: true
      ignore_cache:
        description: Do not used cached images when building
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Base image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: uclatall/{{ github.event.inputs.image }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          snapshot: true
          default_branch: main
          dockerfile: dockerfiles/{{ github.event.inputs.image }}.Dockerfile
          cache: ${{ !github.event.inputs.ignore_cache }}
